### ISSUE TITLE
JdbcSession.execute() doesn't work with MySQL server

### ISSUE THREAD

**Issue by fabriciofx** [jcabi/jcabi-jdbc#46]
Hi!

The following code throws an exception when I try execute the JdbcSession.execute() method with the MySQL server:

Exception:

```
Exception in thread "main" java.sql.SQLException: java.sql.SQLException: Generated keys not requested. You need to specify Statement.RETURN_GENERATED_KEYS to Statement.executeUpdate(), Statement.executeLargeUpdate() or Connection.prepareStatement().
    at com.jcabi.jdbc.JdbcSession.run(JdbcSession.java:395)
    at com.jcabi.jdbc.JdbcSession.execute_aroundBody16(JdbcSession.java:328)
    at com.jcabi.jdbc.JdbcSession$AjcClosure17.run(JdbcSession.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
    at com.jcabi.jdbc.JdbcSession.execute(JdbcSession.java:328)
    at com.github.fabriciofx.dominio.TesteJcabiJdbc.main(TesteJcabiJdbc.java:33)
Caused by: java.sql.SQLException: Generated keys not requested. You need to specify Statement.RETURN_GENERATED_KEYS to Statement.executeUpdate(), Statement.executeLargeUpdate() or Connection.prepareStatement().
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
    at com.mysql.jdbc.StatementImpl.getGeneratedKeys(StatementImpl.java:1682)
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.getGeneratedKeys(HikariProxyPreparedStatement.java)
    at com.jcabi.jdbc.Request$1.fetch(Request.java:55)
    at com.jcabi.jdbc.JdbcSession.run(JdbcSession.java:378)
    ... 8 more
```

and the code:

``` java
public final class TesteJcabiJdbc {
    public static void main(String[] args) throws IOException, SQLException {
        final HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:mysql://localhost/agenda");
        config.setUsername("root");
        config.setPassword("admin");

        final DataSource ds = new HikariDataSource(config);
        new JdbcSession(ds).autocommit(false)
        .sql("CREATE TABLE foo5 (name VARCHAR(30))")
        .execute()
        .sql("DROP TABLE foo5")
        .execute()
        .commit();
    }
}
```

Thanks in advance!

**Comment by fabriciofx** [comment]
@yegor256 , could you see it?

**Comment by yegor256** [comment]
@fabriciofx very strange. Are you sure you're using `execute()`? Looks like you're calling `executeUpdate()`

**Comment by fabriciofx** [comment]
@yegor256 Yes, I'm sure! I did some testing and discover this test code works with PostgreSQL and H2 databases but doesn't work with MySQL. If I change the JdbcSession.execute() method to:
```java
public JdbcSession execute() throws SQLException {
        this.run(
            Outcome.VOID,
            new Connect.WithKeys(this.query), // I changed here!
            Request.EXECUTE
        );
        return this;
 }
```
the test code will works with MySQL and H2 but not with PostgreSQL. Very strange, isn't it? :)

**Comment by yegor256** [comment]
@fabriciofx really strange indeed... so, use either `execute()` or `executeUpdate()`. the first one uses keys, the other one doesn't

**Comment by fabriciofx** [comment]
@yegor256 ok! Thanks!

**Comment by Glusk2** [comment]
The problem is that this library is relying on what appears to me as **undefined behaviour**. 

In the test provided by @fabriciofx something like this happens upon calling `JdbcSession#execute()`:

1.  SQL is issued for execution with the following parameters:
    - `Request.EXECUTE` , `new Connect.Plain(...)`
2. Inside the `Connect.Plain` object a new `PreparedStatement` is created via [Connection#prepareStatement(String sql)](https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#prepareStatement-java.lang.String-)
3. Inside `Request.EXECUTE` the `PreparedStatement` is executed and queried for "generated keys". These are typically, as I understand, `AUTO-INCREMENT` fields that get set upon SQL `INSERT`s
4. An exeception is thrown because we are querying for the "generated keys". Apparently one should specify this via  [Connection#pepare(String sql, int autoGeneratedKeys)](https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html#prepareStatement-java.lang.String-int-) beforehand when working with MySQL. **Note**, the exception is not thrown becaue there are no keys but rather because we did not even specify that we are expecting any! 

[Postgres](https://github.com/pgjdbc/pgjdbc/blob/aca26a07026e9b289a209799ab28131a33b296dd/pgjdbc/src/main/java/org/postgresql/jdbc/PgStatement.java#L1070)'s JDBC implementation simply returns an empty `ResultSet` in such cases and that's why the tests pass. I imagine other DB providers do something similar - I haven't bothered to check since all tests are passing. [MySql (line1851)](http://www.docjar.com/html/api/com/mysql/jdbc/StatementImpl.java.html), however, is throwing an exception.

When you (@fabriciofx) modified the `JdbcSession#execute()` and replaced  `new Connect.Plain(this.query)` with `new Connect.WithKeys(this.query)` you've hacked around the MySql implementation but broke the system that is currently working with Postgres drivers - `org.postgresql.util.PSQLException: ERROR: syntax error at or near "RETURNING"` is thrown. It seems to work with H2 though.

I don't see a nice way to fix this. I've added an `EmptyResultSet` implementation of [ResultSet](http://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html) and put a little `if`[here](https://github.com/jcabi/jcabi-jdbc/blob/1d2093ab94856c93afe5cfda29d9c365b99baaf8/src/main/java/com/jcabi/jdbc/Request.java#L55). [PreparedStatement#execute()](https://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html#execute()) apparently returns `false` if the first result is either `null` (no result) or update count (retrieved by [Statement#getUpdateCount()](https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#getUpdateCount())). While this is extremly ugly it still won't work for all use cases (but it does cover all tests as of right now). 

The problem is even [bigger](http://stackoverflow.com/questions/9696572/queries-returning-multiple-result-sets#answer-33281387)! A single statement may return multiple values - a sort of mixed list of these types:

- `ResultSet`,
- `int` - update count,
- `null`.

**Comment by nshusa** [comment]
I'm actually getting this issue still too... For postgres this library works perfect but for mysql you'll run into this issue on any execute statement.

**Comment by ts14ic** [comment]
Exactly the same problem with MS SQL Server.
https://github.com/ts14ic/JcabiSessionTest

Only `.select()` works, given some `SELECT` query is contained within the sql string or procedure.
Procedures with `NOCOUNT ON` but without `SELECT` queries are also broken.

`.insert()`, .`update()`, `.call()`, `execute()` all fail when `getGeneratedKeys()` is called.

**Comment by strongmuffin** [comment]
Still getting this issue

**Comment by portlek** [comment]
same issue.

**Comment by andreoss** [comment]
@fabriciofx Fixed
