### ISSUE TITLE
Add BigDecimal to SingleOutput?

### ISSUE THREAD

**Issue by miroque** [jcabi/jcabi-jdbc#57]
It's not an issue it's more a proposal. Using this lib with Oracle DB.
But when working with Update ot Insert, oracle jdbc driver returns BigDecimal, which is not an approproate type appropriate in SingleOutput.
Maybe it worth to add it?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@miroque definitely, would be great to extend the lib. Maybe you can submit a pull request? It's really a matter of a few lines.

**Comment by Glusk2** [comment]
@miroque  For the time being, you can use `Outcome<BigDecimal>` and override `handle` method.

**Comment by andreoss** [comment]
@Glusk What was the reason for closing your PR for `BigDecimal`?

**Comment by Glusk** [comment]
@andreoss 
If you look at the complete [diff](https://github.com/jcabi/jcabi-jdbc/pull/59/files) and one of the logs for Travis build [#548](https://travis-ci.org/github/jcabi/jcabi-jdbc/builds/200960749) (build run on 3 different JDKs), you'll notice the error:

> ```
> [ERROR] /src/main/java/com/jcabi/jdbc/PrepareArgs.java[62-86]: The method 'prepare' has a Cyclomatic Complexity of 10. (CyclomaticComplexity)
> [ERROR] /src/main/java/com/jcabi/jdbc/PrepareArgs.java[46-87]: The class 'PrepareArgs' has a Cyclomatic Complexity of 6 (Highest = 10). (CyclomaticComplexity)
> [ERROR] /src/main/java/com/jcabi/jdbc/PrepareArgs.java[62-86]: The method 'prepare' has a Standard Cyclomatic Complexity of 10. (StdCyclomaticComplexity)
> [ERROR] /src/main/java/com/jcabi/jdbc/PrepareArgs.java[46-87]: The class 'PrepareArgs' has a Standard Cyclomatic Complexity of 6 (Highest = 10). (StdCyclomaticComplexity)
> [ERROR] /src/main/java/com/jcabi/jdbc/PrepareArgs.java[62-86]: The method 'prepare' has a Modified Cyclomatic Complexity of 10. (ModifiedCyclomaticComplexity)
> [ERROR] /src/main/java/com/jcabi/jdbc/PrepareArgs.java[46-87]: The class 'PrepareArgs' has a Modified Cyclomatic Complexity of 6 (Highest = 10). (ModifiedCyclomaticComplexity)
> [ERROR] /src/main/java/com/jcabi/jdbc/SingleOutcome.java[137-169]: The method 'fetch' has a Cyclomatic Complexity of 10. (CyclomaticComplexity)
> [ERROR] /src/main/java/com/jcabi/jdbc/SingleOutcome.java[76-171]: The class 'SingleOutcome' has a Cyclomatic Complexity of 6 (Highest = 10). (CyclomaticComplexity)
> [ERROR] /src/main/java/com/jcabi/jdbc/SingleOutcome.java[137-169]: The method 'fetch' has a Standard Cyclomatic Complexity of 10. (StdCyclomaticComplexity)
> [ERROR] /src/main/java/com/jcabi/jdbc/SingleOutcome.java[76-171]: The class 'SingleOutcome' has a Standard Cyclomatic Complexity of 4 (Highest = 10). (StdCyclomaticComplexity)
> [ERROR] /src/main/java/com/jcabi/jdbc/SingleOutcome.java[137-169]: The method 'fetch' has a Modified Cyclomatic Complexity of 10. (ModifiedCyclomaticComplexity)
> [ERROR] /src/main/java/com/jcabi/jdbc/SingleOutcome.java[76-171]: The class 'SingleOutcome' has a Modified Cyclomatic Complexity of 4 (Highest = 10). (ModifiedCyclomaticComplexity)
> ```

_From: https://travis-ci.org/github/jcabi/jcabi-jdbc/jobs/200960750#L961-L972_

---

So the static analysis, PMD in the above case, warned about the _Cyclomatic Complexity_ increasing past the set threshold with my pull request. In other words, the **if** statements got too long!

It is very likely that at the time I didn't know how to suppress PMD warnings. But once I did, I was not really happy with my pull request anymore. It seems like a bad trade-off to lower the bar of static analysis just so that this feature could be added. I've pointed out this issue in #79 and suggested an alternative.

**Comment by andreoss** [comment]
@miroque Fixed
